;===============================================================================
; VTUNECFG - display configuration writer for VibeTune
;===============================================================================

#include "../RomWBW/Source/ver.inc"
#include "../RomWBW/Source/Apps/Tune/cpm.inc"
#include "vtversion.inc"

#DEFINE CFG_MAGIC $A5
#DEFINE MODE_PLAIN 0
#DEFINE MODE_VT100 1
#DEFINE MODE_ANSI  2

#DEFINE ERR_OK      0
#DEFINE ERR_NO_ARG  1
#DEFINE ERR_BAD_ARG 2
#DEFINE ERR_VERIFY  3

#DEFINE CFGSTAT_OK      0
#DEFINE CFGSTAT_MISSING 1
#DEFINE CFGSTAT_INVALID 2

	.ORG	$0100

START:
	CALL	CRLF
	LD	DE, MSG_BANNER
	CALL	PRTSTR
	CALL	CRLF

	CALL	PARSE_MODE_ARG
	OR	A
	JP	Z, START_WRITE
	CP	ERR_VERIFY
	JP	Z, START_VERIFY
	CP	ERR_NO_ARG
	JP	Z, START_SHOW
	LD	DE, MSG_ERR_BAD_ARG
	CALL	PRTSTR
	CALL	CRLF
	JP	START_USAGE

START_SHOW:
	CALL	LOAD_CFG_MODE
	OR	A
	JR	Z, START_SHOW_PRINT
	CP	CFGSTAT_MISSING
	JR	NZ, START_SHOW_INVALID
	LD	DE, MSG_SHOW_MISSING
	CALL	PRTSTR
	CALL	CRLF
	JR	START_SHOW_DEFAULT

START_SHOW_INVALID:
	LD	DE, MSG_SHOW_INVALID
	CALL	PRTSTR
	CALL	CRLF

START_SHOW_DEFAULT:
	XOR	A
	LD	(CFG_MODE), A

START_SHOW_PRINT:
	LD	DE, MSG_SHOW_PREFIX
	CALL	PRTSTR
	LD	A, (CFG_MODE)
	CALL	PRINT_MODE_NAME
	CALL	CRLF
	JP	START_EXIT

START_USAGE:
	LD	DE, MSG_USAGE
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

START_WRITE:
	CALL	CFG_WRITE_FROM_MODE
	OR	A
	JP	NZ, START_WRITE_FAIL

	LD	DE, MSG_OK_PREFIX
	CALL	PRTSTR
	LD	A, (CFG_MODE)
	CALL	PRINT_MODE_NAME
	CALL	CRLF
	JP	START_EXIT

START_VERIFY:
	; Determine baseline mode for roundtrip check.
	CALL	LOAD_CFG_MODE
	OR	A
	JR	Z, START_VERIFY_HAVE_MODE
	XOR	A
	LD	(CFG_MODE), A

START_VERIFY_HAVE_MODE:
	LD	A, (CFG_MODE)
	LD	(BEFORE_MODE), A

	CALL	CFG_WRITE_FROM_MODE
	OR	A
	JR	NZ, START_VERIFY_FAIL

	CALL	LOAD_CFG_MODE
	OR	A
	JR	NZ, START_VERIFY_FAIL

	LD	A, (CFG_MODE)
	LD	B, A
	LD	A, (BEFORE_MODE)
	CP	B
	JR	NZ, START_VERIFY_FAIL

	LD	DE, MSG_VERIFY_OK
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

START_VERIFY_FAIL:
	LD	DE, MSG_VERIFY_FAIL
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

CFG_WRITE_FROM_MODE:
	CALL	BUILD_CFG_FCB

	; Prepare one DMA record (128 bytes), only first 3 bytes are used by vtune.
	LD	HL, DMA_BUFFER
	LD	B, 128
CFG_CLR_DMA:
	XOR	A
	LD	(HL), A
	INC	HL
	DJNZ	CFG_CLR_DMA

	LD	A, CFG_MAGIC
	LD	(DMA_BUFFER), A
	LD	A, (CFG_MODE)
	LD	(DMA_BUFFER+1), A
	XOR	A
	LD	(DMA_BUFFER+2), A

	; Set DMA source for sequential write.
	LD	DE, DMA_BUFFER
	LD	C, $1A
	CALL	BDOS

	; Replace existing file if present.
	LD	DE, CFG_FCB
	LD	C, $13
	CALL	BDOS

	; Create file.
	LD	DE, CFG_FCB
	LD	C, $16
	CALL	BDOS
	CP	$FF
	JR	Z, CFG_WRITE_FAIL

	; Write one 128-byte record.
	LD	DE, CFG_FCB
	LD	C, $15
	CALL	BDOS
	OR	A
	JR	NZ, CFG_WRITE_FAIL

	; Close file.
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	XOR	A
	RET

CFG_WRITE_FAIL:
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, 1
	RET

START_WRITE_FAIL:
	LD	DE, MSG_ERR_WRITE
	CALL	PRTSTR
	CALL	CRLF

START_EXIT:
	; Restore default CP/M DMA before returning.
	LD	DE, $0080
	LD	C, $1A
	CALL	BDOS
	RET

; Load and validate VTUNE.CFG into CFG_MODE.
; Returns A=CFGSTAT_OK, CFGSTAT_MISSING, CFGSTAT_INVALID.
LOAD_CFG_MODE:
	CALL	BUILD_CFG_FCB
	LD	DE, DMA_BUFFER
	LD	C, $1A
	CALL	BDOS
	LD	DE, CFG_FCB
	LD	C, $0F
	CALL	BDOS
	CP	$FF
	JR	Z, LOAD_CFG_MISSING
	LD	DE, CFG_FCB
	LD	C, $14
	CALL	BDOS
	OR	A
	JR	NZ, LOAD_CFG_INVALID_CLOSE
	LD	A, (DMA_BUFFER)
	CP	CFG_MAGIC
	JR	NZ, LOAD_CFG_INVALID_CLOSE
	LD	A, (DMA_BUFFER+1)
	CP	MODE_ANSI + 1
	JR	NC, LOAD_CFG_INVALID_CLOSE
	LD	(CFG_MODE), A
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, CFGSTAT_OK
	RET

LOAD_CFG_INVALID_CLOSE:
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, CFGSTAT_INVALID
	RET

LOAD_CFG_MISSING:
	LD	A, CFGSTAT_MISSING
	RET

; Parse one mode token from command tail.
; Supported values (case-insensitive): PLAIN/0, VT100/1, ANSI/2
; Returns A=ERR_OK and sets CFG_MODE on success.
PARSE_MODE_ARG:
	LD	HL, $0080
	LD	B, (HL)
	INC	HL

PARSE_SKIP_SPACES:
	LD	A, B
	OR	A
	JP	Z, PARSE_NO_ARG
	LD	A, (HL)
	CP	' '
	JR	NZ, PARSE_COPY_START
	INC	HL
	DEC	B
	JR	PARSE_SKIP_SPACES

PARSE_COPY_START:
	LD	DE, ARG_BUFFER
	LD	C, 0
PARSE_COPY_LOOP:
	LD	A, B
	OR	A
	JR	Z, PARSE_COPY_DONE
	LD	A, (HL)
	CP	' '
	JR	Z, PARSE_COPY_DONE
	LD	A, C
	CP	15
	JP	NC, PARSE_BAD_ARG
	LD	A, (HL)
	LD	(DE), A
	INC	DE
	INC	HL
	DEC	B
	INC	C
	JR	PARSE_COPY_LOOP

PARSE_COPY_DONE:
	XOR	A
	LD	(DE), A

	; Skip trailing spaces.
PARSE_TAIL_SPACES:
	LD	A, B
	OR	A
	JR	Z, PARSE_MAP
	LD	A, (HL)
	CP	' '
	JP	NZ, PARSE_BAD_ARG
	INC	HL
	DEC	B
	JR	PARSE_TAIL_SPACES

PARSE_MAP:
	LD	HL, ARG_BUFFER
	LD	A, (HL)
	OR	A
	JP	Z, PARSE_NO_ARG
	LD	DE, TOK_SHOW
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_NO_ARG
	LD	DE, TOK_VERIFY
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_VERIFY

	LD	DE, TOK_PLAIN
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_PLAIN
	LD	DE, TOK_ZERO
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_PLAIN

	LD	DE, TOK_VT100
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_VT100
	LD	DE, TOK_ONE
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_VT100

	LD	DE, TOK_ANSI
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_ANSI
	LD	DE, TOK_TWO
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_ANSI

PARSE_BAD_ARG:
	LD	A, ERR_BAD_ARG
	RET

PARSE_NO_ARG:
	LD	A, ERR_NO_ARG
	RET

PARSE_SET_PLAIN:
	XOR	A
	LD	(CFG_MODE), A
	XOR	A
	RET

PARSE_SET_VT100:
	LD	A, MODE_VT100
	LD	(CFG_MODE), A
	XOR	A
	RET

PARSE_SET_ANSI:
	LD	A, MODE_ANSI
	LD	(CFG_MODE), A
	XOR	A
	RET

PARSE_VERIFY:
	LD	A, ERR_VERIFY
	RET

; Compare zero-terminated ARG_BUFFER token (HL) against token at DE.
; Case-insensitive for A-Z.
; Return A=0 match, A=1 no match.
MATCH_TOKEN:
	PUSH	HL
	PUSH	DE
MATCH_LOOP:
	LD	A, (HL)
	CALL	TO_UPPER
	LD	B, A
	LD	A, (DE)
	CALL	TO_UPPER
	CP	B
	JR	NZ, MATCH_NO
	OR	A
	JR	Z, MATCH_YES
	INC	HL
	INC	DE
	JR	MATCH_LOOP

MATCH_NO:
	POP	DE
	POP	HL
	LD	A, 1
	RET

MATCH_YES:
	POP	DE
	POP	HL
	XOR	A
	RET

TO_UPPER:
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	32
	RET

; Build FCB for VTUNE.CFG in CFG_FCB.
BUILD_CFG_FCB:
	LD	HL, CFG_FCB
	LD	B, 36
CFG_FCB_CLEAR:
	XOR	A
	LD	(HL), A
	INC	HL
	DJNZ	CFG_FCB_CLEAR

	LD	HL, CFG_FCB+1
	LD	DE, CFG_NAME
	LD	B, 11
CFG_FCB_NAME:
	LD	A, (DE)
	LD	(HL), A
	INC	HL
	INC	DE
	DJNZ	CFG_FCB_NAME
	RET

PRINT_MODE_NAME:
	CP	MODE_VT100
	JR	Z, PRINT_MODE_VT100
	CP	MODE_ANSI
	JR	Z, PRINT_MODE_ANSI
	LD	DE, TOK_PLAIN
	JP	PRTSTR
PRINT_MODE_VT100:
	LD	DE, TOK_VT100
	JP	PRTSTR
PRINT_MODE_ANSI:
	LD	DE, TOK_ANSI
	JP	PRTSTR

; Print the zero-terminated string addressed by DE.
PRTSTR:
	PUSH	AF
	PUSH	DE

CFG_PRTSTR_LOOP:
	LD	A, (DE)
	OR	A
	JR	Z, CFG_PRTSTR_DONE
	CALL	PRTCHR
	INC	DE
	JR	CFG_PRTSTR_LOOP

CFG_PRTSTR_DONE:
	POP	DE
	POP	AF
	RET

; Print the character in A via CP/M BDOS function 2.
PRTCHR:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E, A
	LD	C, $02
	CALL	BDOS
	POP	HL
	POP	DE
	POP	BC
	RET

CRLF:
	PUSH	AF
	LD	A, 13
	CALL	PRTCHR
	LD	A, 10
	CALL	PRTCHR
	POP	AF
	RET

MSG_BANNER:
	.DB	"VibeTune Config Utility v", VT_VERSION, ", ", VT_BUILD_DATE, 0
MSG_USAGE:
	.DB	"Usage: VTUNECFG [plain|vt100|ansi|show|verify]", 0
MSG_ERR_BAD_ARG:
	.DB	"Error: mode must be plain, vt100, ansi, show, or verify.", 0
MSG_ERR_WRITE:
	.DB	"Error: unable to write VTUNE.CFG.", 0
MSG_OK_PREFIX:
	.DB	"Wrote VTUNE.CFG mode: ", 0
MSG_SHOW_PREFIX:
	.DB	"Current VTUNE.CFG mode: ", 0
MSG_SHOW_MISSING:
	.DB	"VTUNE.CFG not found; using default mode.", 0
MSG_SHOW_INVALID:
	.DB	"VTUNE.CFG invalid; using default mode.", 0
MSG_VERIFY_OK:
	.DB	"VTUNE.CFG verify: PASS", 0
MSG_VERIFY_FAIL:
	.DB	"VTUNE.CFG verify: FAIL", 0

TOK_PLAIN:
	.DB	"PLAIN", 0
TOK_VT100:
	.DB	"VT100", 0
TOK_ANSI:
	.DB	"ANSI", 0
TOK_ZERO:
	.DB	"0", 0
TOK_ONE:
	.DB	"1", 0
TOK_TWO:
	.DB	"2", 0
TOK_SHOW:
	.DB	"SHOW", 0
TOK_VERIFY:
	.DB	"VERIFY", 0

CFG_NAME:
	.DB	"VTUNE   CFG"

CFG_MODE:
	.DB	MODE_PLAIN
BEFORE_MODE:
	.DB	MODE_PLAIN
ARG_BUFFER:
	.DS	16
CFG_FCB:
	.DS	36
DMA_BUFFER:
	.DS	128

	.END	START
