;===============================================================================
; VTUNECFG - display configuration utility for VibeTune
;
; Copyright (C) 2026, Joao Miguel Duraes (fackie), GNU GPL v3 (or later).
; Derived from the terminal-configuration mode of RomWBW's tune.asm by
; Wayne Warthen (GNU GPL v3).
;
; Writes VTUNE.CFG (128-byte record, first 8 bytes used):
;   byte 0: magic = $A5
;   byte 1: term type (0=plain, 1=VTxxx, 2=ANSI)  -- vtune.com DISP_MODE
;   byte 2: flags (bit 0 = ANSI colour)
;   byte 3: rows (0 -> default 24)
;   byte 4: cols (0 -> default 80)
;   byte 5: TS topology (0=auto, 1=dual-card, 2=single-card dual-AVR module)
;   byte 6: primary AY card (0=auto, 1=MSX, 2=RC, 3=EB, 4=Coleco)
;   byte 7: second AY card for dual-card (0=none, 1..4 as above)
;
; vtune.com: CFG is the default; CLI (-msx/-rc/-eb/-coleco/-tsm) overrides.
;
; Usage: VTUNECFG                interactive configuration (old -config UI)
;        VTUNECFG plain|vt100|ansi|0|1|2   one-shot term type change
;        VTUNECFG show            print current settings
;        VTUNECFG verify          write+read+compare roundtrip check
;===============================================================================

#include "../RomWBW/Source/ver.inc"
#include "../RomWBW/Source/Apps/Tune/cpm.inc"
#include "vtver.inc"

#DEFINE CFG_MAGIC $A5

#DEFINE TERM_PLAIN 0
#DEFINE TERM_VT    1
#DEFINE TERM_ANSI  2

#DEFINE CFGF_ANSI  $01

#DEFINE CFG_MIN_ROWS 8
#DEFINE CFG_MAX_ROWS 50
#DEFINE CFG_MIN_COLS 20
#DEFINE CFG_MAX_COLS 150
#DEFINE CFG_DFL_ROWS 24
#DEFINE CFG_DFL_COLS 80

#DEFINE TS_TOPO_AUTO     0
#DEFINE TS_TOPO_DUALCARD 1
#DEFINE TS_TOPO_MODULE   2

; Match vibetune.asm HW_MODE_* (byte 6/7 of VTUNE.CFG)
#DEFINE AY_CARD_AUTO   0
#DEFINE AY_CARD_MSX    1
#DEFINE AY_CARD_RC     2
#DEFINE AY_CARD_EB     3
#DEFINE AY_CARD_COLECO 4

#DEFINE TCFG_ORG_ROW 5
#DEFINE TCFG_ORG_COL 5

#DEFINE ERR_OK      0
#DEFINE ERR_NO_ARG  1
#DEFINE ERR_BAD_ARG 2
#DEFINE ERR_VERIFY  3
#DEFINE ERR_SHOW    4

#DEFINE CFGSTAT_OK      0
#DEFINE CFGSTAT_MISSING 1
#DEFINE CFGSTAT_INVALID 2

	.ORG	$0100

START:
	CALL	CRLF
	LD	DE, MSG_BANNER
	CALL	PRTSTR
	CALL	CRLF

	CALL	PARSE_MODE_ARG
	OR	A
	JP	Z, START_ONESHOT
	CP	ERR_VERIFY
	JP	Z, START_VERIFY
	CP	ERR_NO_ARG
	JP	Z, START_INTERACTIVE
	CP	ERR_SHOW
	JP	Z, START_SHOW
	LD	DE, MSG_ERR_BAD_ARG
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_USAGE
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

;-------------------------------------------------------------------------------
; One-shot: VTUNECFG plain|vt100|ansi|0|1|2 -- set term type, keep other fields
;-------------------------------------------------------------------------------
START_ONESHOT:
	CALL	CFG_LOAD
	LD	A, (ARG_TERM)
	LD	(CFG_TERM), A
	CALL	CFG_SAVE
	OR	A
	JP	NZ, START_WRITE_FAIL

	LD	DE, MSG_OK_PREFIX
	CALL	PRTSTR
	LD	A, (CFG_TERM)
	CALL	PRINT_TERM_NAME
	CALL	CRLF
	JP	START_EXIT

;-------------------------------------------------------------------------------
; show: print current settings
;-------------------------------------------------------------------------------
START_SHOW:
	CALL	CFG_LOAD
	OR	A
	JR	Z, START_SHOW_PRINT
	CP	CFGSTAT_MISSING
	JR	NZ, START_SHOW_INVALID
	LD	DE, MSG_SHOW_MISSING
	CALL	PRTSTR
	CALL	CRLF
	JR	START_SHOW_PRINT

START_SHOW_INVALID:
	LD	DE, MSG_SHOW_INVALID
	CALL	PRTSTR
	CALL	CRLF

START_SHOW_PRINT:
	CALL	TCFG_PRINT_SUMMARY
	CALL	CRLF
	JP	START_EXIT

;-------------------------------------------------------------------------------
; verify: full-record write + read + compare roundtrip
;-------------------------------------------------------------------------------
START_VERIFY:
	CALL	CFG_LOAD

	LD	HL, CFG_TERM
	LD	DE, BEFORE_TERM
	LD	BC, 7
	LDIR

	CALL	CFG_SAVE
	OR	A
	JR	NZ, START_VERIFY_FAIL

	CALL	CFG_LOAD
	OR	A
	JR	NZ, START_VERIFY_FAIL

	LD	HL, CFG_TERM
	LD	DE, BEFORE_TERM
	LD	B, 7
START_VERIFY_CMP:
	LD	A, (DE)
	CP	(HL)
	JR	NZ, START_VERIFY_FAIL
	INC	HL
	INC	DE
	DJNZ	START_VERIFY_CMP

	LD	DE, MSG_VERIFY_OK
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

START_VERIFY_FAIL:
	LD	DE, MSG_VERIFY_FAIL
	CALL	PRTSTR
	CALL	CRLF
	JP	START_EXIT

;-------------------------------------------------------------------------------
; Interactive configuration (port of the old vtune -config UI)
;-------------------------------------------------------------------------------
START_INTERACTIVE:
	CALL	CFG_LOAD
	LD	(CFG_LOAD_STAT), A

	CALL	FLUSHKEYS
	CALL	TCFG_CLRHOME
	CALL	TCFG_COL_HDR
	LD	DE, MSG_CFGMODE
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	CRLF2

	LD	A, (CFG_LOAD_STAT)
	OR	A
	JR	Z, START_INT_FOUND
	CP	CFGSTAT_MISSING
	JR	NZ, START_INT_INVALID
	LD	DE, MSG_CFGDEFAULT
	JR	START_INT_STATUS
START_INT_INVALID:
	LD	DE, MSG_CFGINVALID
	JR	START_INT_STATUS
START_INT_FOUND:
	LD	DE, MSG_CFGFOUND
START_INT_STATUS:
	CALL	PRTSTR
	CALL	CRLF
	CALL	TCFG_PRINT_SUMMARY
	CALL	CRLF2

	CALL	TCFG_ASK_CARD1
	CALL	TCFG_ASK_TS
	LD	A, (CFG_TSTOPO)
	CP	TS_TOPO_DUALCARD
	CALL	Z, TCFG_ASK_CARD2
	CALL	TCFG_ASK_TERM
	CALL	TCFG_ASK_ANSI

	LD	A, (CFG_TERM)
	OR	A
	JR	NZ, START_INT_TUNE
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	JR	Z, START_INT_SAVE
START_INT_TUNE:
	CALL	TCFG_SIZE_TUNE

START_INT_SAVE:
	CALL	CFG_SAVE
	OR	A
	JP	NZ, START_WRITE_FAIL
	CALL	TCFG_CLRHOME
	CALL	TCFG_COL_OK
	LD	DE, MSG_CFGSAVED
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	CRLF
	CALL	TCFG_PRINT_SUMMARY
	CALL	CRLF2
	CALL	FLUSHKEYS
	JP	START_EXIT

START_WRITE_FAIL:
	LD	DE, MSG_ERR_WRITE
	CALL	PRTSTR
	CALL	CRLF

START_EXIT:
	; Restore default CP/M DMA before returning.
	LD	DE, $0080
	LD	C, $1A
	CALL	BDOS
	RET

;===============================================================================
; Config file load/save
;===============================================================================

CFG_DEFAULTS:
	XOR	A
	LD	(CFG_TERM), A
	LD	(CFG_FLAGS), A
	LD	(CFG_TSTOPO), A
	LD	(CFG_CARD1), A
	LD	(CFG_CARD2), A
	LD	A, CFG_DFL_ROWS
	LD	(CFG_ROWS), A
	LD	A, CFG_DFL_COLS
	LD	(CFG_COLS), A
	RET

; Load VTUNE.CFG into CFG_* (defaults preloaded).
; Returns A=CFGSTAT_OK, CFGSTAT_MISSING, CFGSTAT_INVALID.
CFG_LOAD:
	CALL	CFG_DEFAULTS
	CALL	BUILD_CFG_FCB
	LD	DE, DMA_BUFFER
	LD	C, $1A
	CALL	BDOS
	LD	DE, CFG_FCB
	LD	C, $0F
	CALL	BDOS
	CP	$FF
	JR	Z, CFG_LOAD_MISSING
	XOR	A
	LD	(DMA_BUFFER+5), A	; short/old file -> TS auto, cards auto/none
	LD	(DMA_BUFFER+6), A
	LD	(DMA_BUFFER+7), A
	LD	DE, CFG_FCB
	LD	C, $14
	CALL	BDOS
	OR	A
	JR	NZ, CFG_LOAD_INVALID
	LD	A, (DMA_BUFFER)
	CP	CFG_MAGIC
	JR	NZ, CFG_LOAD_INVALID

	LD	A, (DMA_BUFFER+1)
	CP	3
	JR	C, CFG_LOAD_TERM_OK
	XOR	A
CFG_LOAD_TERM_OK:
	LD	(CFG_TERM), A
	LD	A, (DMA_BUFFER+2)
	AND	CFGF_ANSI
	LD	(CFG_FLAGS), A
	LD	A, (DMA_BUFFER+3)
	OR	A
	JR	NZ, CFG_LOAD_ROWS_OK
	LD	A, CFG_DFL_ROWS
CFG_LOAD_ROWS_OK:
	LD	(CFG_ROWS), A
	LD	A, (DMA_BUFFER+4)
	OR	A
	JR	NZ, CFG_LOAD_COLS_OK
	LD	A, CFG_DFL_COLS
CFG_LOAD_COLS_OK:
	LD	(CFG_COLS), A
	LD	A, (DMA_BUFFER+5)
	CP	3
	JR	C, CFG_LOAD_TS_OK
	XOR	A
CFG_LOAD_TS_OK:
	LD	(CFG_TSTOPO), A
	LD	A, (DMA_BUFFER+6)
	CP	5
	JR	C, CFG_LOAD_C1_OK
	XOR	A
CFG_LOAD_C1_OK:
	LD	(CFG_CARD1), A
	LD	A, (DMA_BUFFER+7)
	CP	5
	JR	C, CFG_LOAD_C2_OK
	XOR	A
CFG_LOAD_C2_OK:
	LD	(CFG_CARD2), A

	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, CFGSTAT_OK
	RET

CFG_LOAD_INVALID:
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, CFGSTAT_INVALID
	RET

CFG_LOAD_MISSING:
	LD	A, CFGSTAT_MISSING
	RET

; Write CFG_* to VTUNE.CFG. Returns A=0 ok, A=1 fail.
CFG_SAVE:
	CALL	BUILD_CFG_FCB

	; Prepare one DMA record (128 bytes), first 8 bytes used.
	LD	HL, DMA_BUFFER
	LD	B, 128
CFG_SAVE_CLR:
	XOR	A
	LD	(HL), A
	INC	HL
	DJNZ	CFG_SAVE_CLR

	LD	A, CFG_MAGIC
	LD	(DMA_BUFFER), A
	LD	A, (CFG_TERM)
	LD	(DMA_BUFFER+1), A
	LD	A, (CFG_FLAGS)
	LD	(DMA_BUFFER+2), A
	LD	A, (CFG_ROWS)
	LD	(DMA_BUFFER+3), A
	LD	A, (CFG_COLS)
	LD	(DMA_BUFFER+4), A
	LD	A, (CFG_TSTOPO)
	LD	(DMA_BUFFER+5), A
	LD	A, (CFG_CARD1)
	LD	(DMA_BUFFER+6), A
	LD	A, (CFG_CARD2)
	LD	(DMA_BUFFER+7), A

	LD	DE, DMA_BUFFER
	LD	C, $1A
	CALL	BDOS

	; Replace existing file if present.
	LD	DE, CFG_FCB
	LD	C, $13
	CALL	BDOS

	; Create file.
	LD	DE, CFG_FCB
	LD	C, $16
	CALL	BDOS
	CP	$FF
	JR	Z, CFG_SAVE_FAIL

	; Write one 128-byte record.
	LD	DE, CFG_FCB
	LD	C, $15
	CALL	BDOS
	OR	A
	JR	NZ, CFG_SAVE_FAIL

	; Close file.
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	XOR	A
	RET

CFG_SAVE_FAIL:
	LD	DE, CFG_FCB
	LD	C, $10
	CALL	BDOS
	LD	A, 1
	RET

; Build FCB for VTUNE.CFG in CFG_FCB.
BUILD_CFG_FCB:
	LD	HL, CFG_FCB
	LD	B, 36
BUILD_CFG_CLR:
	XOR	A
	LD	(HL), A
	INC	HL
	DJNZ	BUILD_CFG_CLR

	LD	HL, CFG_FCB+1
	LD	DE, CFG_NAME
	LD	B, 11
BUILD_CFG_NAME:
	LD	A, (DE)
	LD	(HL), A
	INC	HL
	INC	DE
	DJNZ	BUILD_CFG_NAME
	RET

;===============================================================================
; Interactive configuration UI (port of old vtune -config / termcfg code)
;===============================================================================

TCFG_PRINT_SUMMARY:
	LD	DE, MSG_CFGCARD1
	CALL	PRTSTR
	LD	A, (CFG_CARD1)
	CALL	PRINT_CARD_NAME
	CALL	CRLF
	LD	DE, MSG_CFGTS
	CALL	PRTSTR
	LD	A, (CFG_TSTOPO)
	CALL	PRINT_TS_NAME
	CALL	CRLF
	LD	A, (CFG_TSTOPO)
	CP	TS_TOPO_DUALCARD
	JR	NZ, TCFG_SUMMARY_TERM
	LD	DE, MSG_CFGCARD2
	CALL	PRTSTR
	LD	A, (CFG_CARD2)
	CALL	PRINT_CARD_NAME
	CALL	CRLF
TCFG_SUMMARY_TERM:
	LD	DE, MSG_CFGTERM
	CALL	PRTSTR
	LD	A, (CFG_TERM)
	CALL	PRINT_TERM_NAME
	CALL	CRLF
	LD	DE, MSG_CFGANSI
	CALL	PRTSTR
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	LD	DE, MSG_NO
	JR	Z, TCFG_SUMMARY0
	LD	DE, MSG_YES
TCFG_SUMMARY0:
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_CFGSIZE
	CALL	PRTSTR
	LD	A, (CFG_COLS)
	CALL	PRTDECB
	LD	A, ' '
	CALL	PRTCHR
	LD	A, 'x'
	CALL	PRTCHR
	LD	A, ' '
	CALL	PRTCHR
	LD	A, (CFG_ROWS)
	CALL	PRTDECB
	RET

PRINT_TERM_NAME:
	CP	TERM_VT
	JR	Z, PRINT_TERM_VT
	CP	TERM_ANSI
	JR	Z, PRINT_TERM_ANSI
	LD	DE, MSG_TERM_PLAIN
	JP	PRTSTR
PRINT_TERM_VT:
	LD	DE, MSG_TERM_VT
	JP	PRTSTR
PRINT_TERM_ANSI:
	LD	DE, MSG_TERM_ANSI
	JP	PRTSTR

TCFG_ASK_TERM:
TCFG_ASK_TERM0:
	CALL	TCFG_COL_PRM
	LD	DE, MSG_TERMMENU
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_TERMPROMPT
	CALL	PRTSTR
	LD	A, (CFG_TERM)
	CALL	PRINT_TERM_NAME
	LD	DE, MSG_PROMPTEND
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	TCFG_GETCH
	CP	13
	JR	Z, TCFG_ASK_TERM_KEEP
	PUSH	AF
	CALL	PRTCHR
	CALL	CRLF
	POP	AF
	CALL	TO_UPPER
	CP	'P'
	JR	Z, TCFG_ASK_TERM_PLAIN
	CP	'V'
	JR	Z, TCFG_ASK_TERM_VT
	CP	'A'
	JR	Z, TCFG_ASK_TERM_ANSI
	JR	TCFG_ASK_TERM0
TCFG_ASK_TERM_KEEP:
	CALL	CRLF
	RET
TCFG_ASK_TERM_PLAIN:
	XOR	A
	LD	(CFG_TERM), A
	RET
TCFG_ASK_TERM_VT:
	LD	A, TERM_VT
	LD	(CFG_TERM), A
	RET
TCFG_ASK_TERM_ANSI:
	LD	A, TERM_ANSI
	LD	(CFG_TERM), A
	RET

TCFG_ASK_ANSI:
TCFG_ASK_ANSI0:
	CALL	TCFG_COL_PRM
	LD	DE, MSG_ANSIPROMPT
	CALL	PRTSTR
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	LD	DE, MSG_NO
	JR	Z, TCFG_ASK_ANSI1
	LD	DE, MSG_YES
TCFG_ASK_ANSI1:
	CALL	PRTSTR
	LD	DE, MSG_PROMPTEND
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	TCFG_GETCH
	CP	13
	JR	Z, TCFG_ASK_ANSI_KEEP
	PUSH	AF
	CALL	PRTCHR
	CALL	CRLF
	POP	AF
	CALL	TO_UPPER
	CP	'Y'
	JR	Z, TCFG_ASK_ANSI_YES
	CP	'N'
	JR	Z, TCFG_ASK_ANSI_NO
	JR	TCFG_ASK_ANSI0
TCFG_ASK_ANSI_KEEP:
	CALL	CRLF
	RET
TCFG_ASK_ANSI_YES:
	LD	A, (CFG_FLAGS)
	OR	CFGF_ANSI
	LD	(CFG_FLAGS), A
	RET
TCFG_ASK_ANSI_NO:
	LD	A, (CFG_FLAGS)
	AND	$FF-CFGF_ANSI
	LD	(CFG_FLAGS), A
	RET

;-------------------------------------------------------------------------------
; Primary AY card (first interactive question)
;-------------------------------------------------------------------------------
TCFG_ASK_CARD1:
TCFG_ASK_CARD1_0:
	CALL	TCFG_COL_PRM
	LD	DE, MSG_CARD1MENU
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_CARDPROMPT
	CALL	PRTSTR
	LD	A, (CFG_CARD1)
	CALL	PRINT_CARD_NAME
	LD	DE, MSG_PROMPTEND
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	TCFG_GETCH
	CP	13
	JR	Z, TCFG_ASK_CARD1_KEEP
	PUSH	AF
	CALL	PRTCHR
	CALL	CRLF
	POP	AF
	CALL	TO_UPPER
	CP	'A'
	JR	Z, TCFG_ASK_C1_AUTO
	CP	'M'
	JR	Z, TCFG_ASK_C1_MSX
	CP	'R'
	JR	Z, TCFG_ASK_C1_RC
	CP	'E'
	JR	Z, TCFG_ASK_C1_EB
	CP	'C'
	JR	Z, TCFG_ASK_C1_COLECO
	JR	TCFG_ASK_CARD1_0
TCFG_ASK_CARD1_KEEP:
	CALL	CRLF
	RET
TCFG_ASK_C1_AUTO:
	XOR	A
	LD	(CFG_CARD1), A
	RET
TCFG_ASK_C1_MSX:
	LD	A, AY_CARD_MSX
	LD	(CFG_CARD1), A
	RET
TCFG_ASK_C1_RC:
	LD	A, AY_CARD_RC
	LD	(CFG_CARD1), A
	RET
TCFG_ASK_C1_EB:
	LD	A, AY_CARD_EB
	LD	(CFG_CARD1), A
	RET
TCFG_ASK_C1_COLECO:
	LD	A, AY_CARD_COLECO
	LD	(CFG_CARD1), A
	RET

;-------------------------------------------------------------------------------
; Second AY card (dual-card topology only). Must be a concrete port set.
;-------------------------------------------------------------------------------
TCFG_ASK_CARD2:
TCFG_ASK_CARD2_0:
	CALL	TCFG_COL_PRM
	LD	DE, MSG_CARD2MENU
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_CARDPROMPT
	CALL	PRTSTR
	LD	A, (CFG_CARD2)
	OR	A
	JR	NZ, TCFG_ASK_CARD2_CUR
	LD	DE, MSG_CARD_NONE
	CALL	PRTSTR
	JR	TCFG_ASK_CARD2_PR
TCFG_ASK_CARD2_CUR:
	CALL	PRINT_CARD_NAME
TCFG_ASK_CARD2_PR:
	LD	DE, MSG_PROMPTEND
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	TCFG_GETCH
	CP	13
	JR	Z, TCFG_ASK_CARD2_KEEP
	PUSH	AF
	CALL	PRTCHR
	CALL	CRLF
	POP	AF
	CALL	TO_UPPER
	CP	'M'
	JR	Z, TCFG_ASK_C2_MSX
	CP	'R'
	JR	Z, TCFG_ASK_C2_RC
	CP	'E'
	JR	Z, TCFG_ASK_C2_EB
	CP	'C'
	JR	Z, TCFG_ASK_C2_COLECO
	JR	TCFG_ASK_CARD2_0
TCFG_ASK_CARD2_KEEP:
	CALL	CRLF
	LD	A, (CFG_CARD2)
	OR	A
	JR	Z, TCFG_ASK_CARD2_0	; must pick a second card
	LD	B, A
	LD	A, (CFG_CARD1)
	CP	B
	JR	Z, TCFG_ASK_CARD2_SAME
	RET
TCFG_ASK_CARD2_SAME:
	LD	DE, MSG_CARD_SAME
	CALL	PRTSTR
	CALL	CRLF
	JR	TCFG_ASK_CARD2_0
TCFG_ASK_C2_MSX:
	LD	A, AY_CARD_MSX
	JR	TCFG_ASK_C2_STORE
TCFG_ASK_C2_RC:
	LD	A, AY_CARD_RC
	JR	TCFG_ASK_C2_STORE
TCFG_ASK_C2_EB:
	LD	A, AY_CARD_EB
	JR	TCFG_ASK_C2_STORE
TCFG_ASK_C2_COLECO:
	LD	A, AY_CARD_COLECO
TCFG_ASK_C2_STORE:
	LD	B, A
	LD	A, (CFG_CARD1)
	CP	B
	LD	A, B
	JR	Z, TCFG_ASK_CARD2_SAME
	LD	(CFG_CARD2), A
	RET

PRINT_CARD_NAME:
	CP	AY_CARD_MSX
	JR	Z, PRINT_CARD_MSX
	CP	AY_CARD_RC
	JR	Z, PRINT_CARD_RC
	CP	AY_CARD_EB
	JR	Z, PRINT_CARD_EB
	CP	AY_CARD_COLECO
	JR	Z, PRINT_CARD_COLECO
	LD	DE, MSG_CARD_AUTO
	JP	PRTSTR
PRINT_CARD_MSX:
	LD	DE, MSG_CARD_MSX
	JP	PRTSTR
PRINT_CARD_RC:
	LD	DE, MSG_CARD_RC
	JP	PRTSTR
PRINT_CARD_EB:
	LD	DE, MSG_CARD_EB
	JP	PRTSTR
PRINT_CARD_COLECO:
	LD	DE, MSG_CARD_COLECO
	JP	PRTSTR

;-------------------------------------------------------------------------------
; TurboSound hardware topology: 0=auto, 1=dual-card, 2=AVR module
;-------------------------------------------------------------------------------
TCFG_ASK_TS:
TCFG_ASK_TS0:
	CALL	TCFG_COL_PRM
	LD	DE, MSG_TSMENU
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_TSPROMPT
	CALL	PRTSTR
	LD	A, (CFG_TSTOPO)
	CALL	PRINT_TS_NAME
	LD	DE, MSG_PROMPTEND
	CALL	PRTSTR
	CALL	TCFG_COL_RST
	CALL	TCFG_GETCH
	CP	13
	JR	Z, TCFG_ASK_TS_KEEP
	PUSH	AF
	CALL	PRTCHR
	CALL	CRLF
	POP	AF
	CALL	TO_UPPER
	CP	'A'
	JR	Z, TCFG_ASK_TS_AUTO
	CP	'D'
	JR	Z, TCFG_ASK_TS_DUAL
	CP	'M'
	JR	Z, TCFG_ASK_TS_MOD
	JR	TCFG_ASK_TS0
TCFG_ASK_TS_KEEP:
	CALL	CRLF
	RET
TCFG_ASK_TS_AUTO:
	XOR	A
	LD	(CFG_TSTOPO), A
	XOR	A
	LD	(CFG_CARD2), A
	RET
TCFG_ASK_TS_DUAL:
	LD	A, TS_TOPO_DUALCARD
	LD	(CFG_TSTOPO), A
	RET
TCFG_ASK_TS_MOD:
	LD	A, TS_TOPO_MODULE
	LD	(CFG_TSTOPO), A
	XOR	A
	LD	(CFG_CARD2), A
	RET

PRINT_TS_NAME:
	CP	TS_TOPO_DUALCARD
	JR	Z, PRINT_TS_DUAL
	CP	TS_TOPO_MODULE
	JR	Z, PRINT_TS_MOD
	LD	DE, MSG_TS_AUTO
	JP	PRTSTR
PRINT_TS_DUAL:
	LD	DE, MSG_TS_DUAL
	JP	PRTSTR
PRINT_TS_MOD:
	LD	DE, MSG_TS_MOD
	JP	PRTSTR

;-------------------------------------------------------------------------------
; Interactive screen size tuning grid
;-------------------------------------------------------------------------------

TCFG_SIZE_TUNE:
	CALL	TCFG_CLRHOME
	LD	DE, MSG_TUNETITLE
	CALL	PRTSTR
	CALL	CRLF
	LD	DE, MSG_TUNEKEYS
	CALL	PRTSTR
	CALL	CRLF
	XOR	A
	LD	(TCFG_PREV_COLS), A
	LD	(TCFG_PREV_ROWS), A
	CALL	TCFG_SIZE_REFRESH

	LD	B, 4
	LD	C, 1
	CALL	TCFG_ANSI_AT
TCFG_SIZE_TUNE0:
	LD	B, 4
	LD	C, 1
	CALL	TCFG_ANSI_AT
	CALL	TCFG_SIZE_GETKEY
	CP	27
	JP	Z, TCFG_SIZE_EXIT
	CP	'a'
	JP	Z, TCFG_SIZE_COL_DEC
	CP	'd'
	JP	Z, TCFG_SIZE_COL_INC
	CP	'w'
	JP	Z, TCFG_SIZE_ROW_DEC
	CP	's'
	JP	Z, TCFG_SIZE_ROW_INC
	JP	TCFG_SIZE_TUNE0

TCFG_SIZE_GETKEY:
	CALL	TCFG_GETCH
	CP	27
	RET	NZ
	; Esc may start an arrow CSI (Esc [ A). Poll briefly for a follower;
	; do not call blocking GETKEY with no char ready (ZPM3/BDOS 6 can
	; wait forever — that forced a second Esc to "complete" the wait).
	CALL	TCFG_GETCH_TO
	OR	A
	JR	Z, TCFG_SIZE_GETKEY_ESC
	CP	27
	JR	Z, TCFG_SIZE_GETKEY_ESC	; Esc Esc → quit
	CP	'['
	JR	Z, TCFG_SIZE_GETKEY_SEQ
	CP	'O'
	JR	Z, TCFG_SIZE_GETKEY_SEQ
	LD	A, 27
	RET

TCFG_SIZE_GETKEY_SEQ:
TCFG_SIZE_GETKEY_SEQ0:
	CALL	TCFG_GETCH_TO
	OR	A
	JR	Z, TCFG_SIZE_GETKEY_ESC
	CP	'0'
	JR	C, TCFG_SIZE_GETKEY_SEQ1
	CP	$3A
	JR	C, TCFG_SIZE_GETKEY_SEQ0
	CP	$3B
	JR	Z, TCFG_SIZE_GETKEY_SEQ0
	CP	$3F
	JR	Z, TCFG_SIZE_GETKEY_SEQ0

TCFG_SIZE_GETKEY_SEQ1:
	CP	'A'
	JR	Z, TCFG_SIZE_GETKEY_UP
	CP	'B'
	JR	Z, TCFG_SIZE_GETKEY_DOWN
	CP	'C'
	JR	Z, TCFG_SIZE_GETKEY_RIGHT
	CP	'D'
	JR	Z, TCFG_SIZE_GETKEY_LEFT
	CP	$40
	JR	C, TCFG_SIZE_GETKEY_SEQ0
	CP	$7F
	JR	C, TCFG_SIZE_GETKEY_ESC	; unknown Esc-seq → quit (was: ignore)
	JR	TCFG_SIZE_GETKEY_SEQ0

TCFG_SIZE_GETKEY_UP:
	LD	A, 'w'
	RET

TCFG_SIZE_GETKEY_DOWN:
	LD	A, 's'
	RET

TCFG_SIZE_GETKEY_RIGHT:
	LD	A, 'd'
	RET

TCFG_SIZE_GETKEY_LEFT:
	LD	A, 'a'
	RET

TCFG_SIZE_GETKEY_ESC:
	LD	A, 27
	RET

; Non-blocking peek with short spin. A=char (NZ) or A=0 (Z) on timeout.
; Uses BDOS CONST (11) so we never block in GETKEY when the buffer is empty.
TCFG_GETCH_TO:
	LD	BC, 8000		; ~brief settle for CSI tails on serial
TCFG_GETCH_TO0:
	PUSH	BC
	LD	C, 11			; BDOS console status
	CALL	BDOS
	OR	A
	JR	Z, TCFG_GETCH_TO1
	CALL	GETKEY
	POP	BC
	OR	A
	RET	NZ
	JR	TCFG_GETCH_TO2
TCFG_GETCH_TO1:
	POP	BC
TCFG_GETCH_TO2:
	DEC	BC
	LD	A, B
	OR	C
	JR	NZ, TCFG_GETCH_TO0
	XOR	A
	RET

TCFG_SIZE_EXIT:
	CALL	FLUSHKEYS
	CALL	TCFG_CLRHOME
	RET

TCFG_SIZE_COL_DEC:
	LD	A, (CFG_COLS)
	CP	CFG_MIN_COLS
	JP	Z, TCFG_SIZE_TUNE0
	CALL	TCFG_SIZE_SNAPSHOT
	LD	A, (CFG_COLS)
	DEC	A
	LD	(CFG_COLS), A
	CALL	TCFG_SIZE_REFRESH
	JP	TCFG_SIZE_TUNE0

TCFG_SIZE_COL_INC:
	LD	A, (CFG_COLS)
	CP	CFG_MAX_COLS
	JP	Z, TCFG_SIZE_TUNE0
	CALL	TCFG_SIZE_SNAPSHOT
	LD	A, (CFG_COLS)
	INC	A
	LD	(CFG_COLS), A
	CALL	TCFG_SIZE_REFRESH
	JP	TCFG_SIZE_TUNE0

TCFG_SIZE_ROW_DEC:
	LD	A, (CFG_ROWS)
	CP	CFG_MIN_ROWS
	JP	Z, TCFG_SIZE_TUNE0
	CALL	TCFG_SIZE_SNAPSHOT
	LD	A, (CFG_ROWS)
	DEC	A
	LD	(CFG_ROWS), A
	CALL	TCFG_SIZE_REFRESH
	JP	TCFG_SIZE_TUNE0

TCFG_SIZE_ROW_INC:
	LD	A, (CFG_ROWS)
	CP	CFG_MAX_ROWS
	JP	Z, TCFG_SIZE_TUNE0
	CALL	TCFG_SIZE_SNAPSHOT
	LD	A, (CFG_ROWS)
	INC	A
	LD	(CFG_ROWS), A
	CALL	TCFG_SIZE_REFRESH
	JP	TCFG_SIZE_TUNE0

TCFG_SIZE_SNAPSHOT:
	LD	A, (CFG_COLS)
	LD	(TCFG_PREV_COLS), A
	LD	A, (CFG_ROWS)
	LD	(TCFG_PREV_ROWS), A
	RET

TCFG_SIZE_REFRESH:
	CALL	TCFG_SIZE_SHOW_CURR
	LD	A, (TCFG_PREV_COLS)
	OR	A
	JR	Z, TCFG_SIZE_REFRESH0
	LD	A, (TCFG_PREV_ROWS)
	OR	A
	JR	Z, TCFG_SIZE_REFRESH0
	LD	A, (CFG_COLS)
	LD	B, A
	LD	A, (TCFG_PREV_COLS)
	CP	B
	CALL	NZ, TCFG_SIZE_UPDATE_COLS
	LD	A, (CFG_ROWS)
	LD	B, A
	LD	A, (TCFG_PREV_ROWS)
	CP	B
	CALL	NZ, TCFG_SIZE_UPDATE_ROWS
	CALL	TCFG_DRAW_SCALES
	JR	TCFG_SIZE_REFRESH1
TCFG_SIZE_REFRESH0:
	CALL	TCFG_DRAW_GRID
TCFG_SIZE_REFRESH1:
	CALL	TCFG_SIZE_SNAPSHOT
	RET

TCFG_SIZE_SHOW_CURR:
	LD	B, 3
	LD	C, 1
	CALL	TCFG_ANSI_AT
	CALL	TCFG_EL2
	LD	B, 3
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	DE, MSG_TUNECURR
	CALL	PRTSTR
	LD	A, (CFG_COLS)
	CALL	PRTDECB
	LD	A, ' '
	CALL	PRTCHR
	LD	A, 'x'
	CALL	PRTCHR
	LD	A, ' '
	CALL	PRTCHR
	LD	A, (CFG_ROWS)
	CALL	PRTDECB
	LD	DE, MSG_TUNEMAX
	CALL	PRTSTR
	RET

TCFG_SIZE_UPDATE_COLS:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A, (TCFG_PREV_COLS)
	LD	D, A			; old cols
	LD	A, (CFG_COLS)
	LD	E, A			; new cols
	CP	D
	JR	C, TCFG_SIZE_UCOLS_DEC

	; expanding width: old C becomes '-', new endpoint gets C
	LD	B, TCFG_ORG_ROW
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, '-'
	CALL	PRTCHR

	LD	A, E
	CALL	TCFG_SIZE_IS_DECADE
	JR	Z, TCFG_SIZE_UCOLS_INC0
	LD	B, TCFG_ORG_ROW - 1
	LD	A, E
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, E
	CALL	PRTDECB
TCFG_SIZE_UCOLS_INC0:
	JR	TCFG_SIZE_UCOLS_SETC

TCFG_SIZE_UCOLS_DEC:
	; shrinking width: erase old C endpoint, new endpoint gets C
	LD	B, TCFG_ORG_ROW
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR

	LD	A, D
	CALL	TCFG_SIZE_IS_DECADE
	JR	Z, TCFG_SIZE_UCOLS_SETC
	LD	B, TCFG_ORG_ROW - 1
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	CALL	PRTCHR
	CALL	PRTCHR

TCFG_SIZE_UCOLS_SETC:
	LD	B, TCFG_ORG_ROW
	LD	A, E
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, 'C'
	CALL	PRTCHR

	; move X marker horizontally
	LD	A, (TCFG_PREV_ROWS)
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	LD	A, (CFG_ROWS)
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	A, E
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, 'X'
	CALL	PRTCHR

	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_SIZE_UPDATE_ROWS:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A, (TCFG_PREV_ROWS)
	LD	D, A			; old rows
	LD	A, (CFG_ROWS)
	LD	E, A			; new rows
	CP	D
	JR	C, TCFG_SIZE_UROWS_DEC

	; expanding height: old R becomes '|', new endpoint gets R
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, '|'
	CALL	PRTCHR

	LD	A, E
	CALL	TCFG_SIZE_IS_DECADE
	JR	Z, TCFG_SIZE_UROWS_INC0
	LD	A, E
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, E
	CALL	PRTDECB
TCFG_SIZE_UROWS_INC0:
	JR	TCFG_SIZE_UROWS_SETR

TCFG_SIZE_UROWS_DEC:
	; shrinking height: erase old R endpoint, new endpoint gets R
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR

	LD	A, D
	CALL	TCFG_SIZE_IS_DECADE
	JR	Z, TCFG_SIZE_UROWS_SETR
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	CALL	PRTCHR
	CALL	PRTCHR

TCFG_SIZE_UROWS_SETR:
	LD	A, E
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, 'R'
	CALL	PRTCHR

	; move X marker vertically
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	A, (TCFG_PREV_COLS)
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	LD	A, E
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	A, (CFG_COLS)
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, 'X'
	CALL	PRTCHR

	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_SIZE_IS_DECADE:
	; IN: A=value, OUT: NZ if value is an exact multiple of 10, else Z
	CP	10
	JR	C, TCFG_SIZE_IS_DEC0
TCFG_SIZE_IS_DEC1:
	SUB	10
	JR	Z, TCFG_SIZE_IS_DEC2
	JR	NC, TCFG_SIZE_IS_DEC1
TCFG_SIZE_IS_DEC0:
	XOR	A
	RET
TCFG_SIZE_IS_DEC2:
	LD	A, 1
	OR	A			; clear Z: LD does not affect flags (old bug:
	RET				; decade case fell through with Z still set)

TCFG_DRAW_SCALES:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL

	; top ruler labels (1, then decades)
	LD	B, TCFG_ORG_ROW - 1
	LD	C, 1
	CALL	TCFG_ANSI_AT
	CALL	TCFG_EL2

	LD	B, TCFG_ORG_ROW - 1
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, '1'
	CALL	PRTCHR

	LD	D, 10
TCFG_DRAW_SCALES_TOP:
	LD	A, (CFG_COLS)
	CP	D
	JR	C, TCFG_DRAW_SCALES_LEFT
	LD	B, TCFG_ORG_ROW - 1
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, D
	PUSH	DE
	CALL	PRTDECB
	POP	DE
	LD	A, D
	ADD	A, 10
	LD	D, A
	JR	TCFG_DRAW_SCALES_TOP

	; left ruler labels (decades only)
TCFG_DRAW_SCALES_LEFT:
	LD	D, 10
TCFG_DRAW_SCALES_LEFT0:
	LD	A, D
	CP	CFG_MAX_ROWS + 1
	JR	NC, TCFG_DRAW_SCALES_DONE

	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	CALL	PRTCHR
	CALL	PRTCHR

	LD	A, (CFG_ROWS)
	CP	D
	JR	C, TCFG_DRAW_SCALES_LEFT1
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, D
	CALL	PRTDECB

TCFG_DRAW_SCALES_LEFT1:
	LD	A, D
	ADD	A, 10
	LD	D, A
	JR	TCFG_DRAW_SCALES_LEFT0

TCFG_DRAW_SCALES_DONE:
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_CLEAR_SCALE:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL

	; clear top ruler line so removed column decades disappear
	LD	B, TCFG_ORG_ROW - 1
	LD	C, 1
	CALL	TCFG_ANSI_AT
	CALL	TCFG_EL2

	; clear left ruler gutter on full tuning height
	LD	D, TCFG_ORG_ROW
TCFG_CLEAR_SCALE0:
	LD	A, D
	CP	TCFG_ORG_ROW + CFG_MAX_ROWS
	JR	NC, TCFG_CLEAR_SCALE1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, ' '
	CALL	PRTCHR
	CALL	PRTCHR
	CALL	PRTCHR
	CALL	PRTCHR
	INC	D
	JR	TCFG_CLEAR_SCALE0
TCFG_CLEAR_SCALE1:
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_DRAW_GRID:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	TCFG_CLEAR_SCALE

	LD	B, TCFG_ORG_ROW
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, '+'
	CALL	PRTCHR

	LD	D, 2
TCFG_HLINE_LOOP:
	LD	A, (CFG_COLS)
	CP	D
	JR	C, TCFG_HLINE_DONE
	LD	B, TCFG_ORG_ROW
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, '-'
	CALL	PRTCHR
	INC	D
	JR	TCFG_HLINE_LOOP
TCFG_HLINE_DONE:

	LD	D, 2
TCFG_VLINE_LOOP:
	LD	A, (CFG_ROWS)
	CP	D
	JR	C, TCFG_VLINE_DONE
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, '|'
	CALL	PRTCHR
	INC	D
	JR	TCFG_VLINE_LOOP
TCFG_VLINE_DONE:

	LD	B, TCFG_ORG_ROW - 1
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, '1'
	CALL	PRTCHR

	LD	B, TCFG_ORG_ROW
	LD	C, TCFG_ORG_COL - 1
	CALL	TCFG_ANSI_AT
	LD	A, '1'
	CALL	PRTCHR

	LD	D, 10
TCFG_TOP_SCALE_LOOP:
	LD	A, (CFG_COLS)
	CP	D
	JR	C, TCFG_TOP_SCALE_DONE
	LD	B, TCFG_ORG_ROW - 1
	LD	A, D
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, D
	PUSH	DE
	CALL	PRTDECB
	POP	DE
	LD	A, D
	ADD	A, 10
	JR	C, TCFG_TOP_SCALE_DONE
	LD	D, A
	JR	TCFG_TOP_SCALE_LOOP
TCFG_TOP_SCALE_DONE:

	LD	D, 10
TCFG_LEFT_SCALE_LOOP:
	LD	A, (CFG_ROWS)
	CP	D
	JR	C, TCFG_LEFT_SCALE_DONE
	LD	A, D
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, 1
	CALL	TCFG_ANSI_AT
	LD	A, D
	PUSH	DE
	CALL	PRTDECB
	POP	DE
	LD	A, D
	ADD	A, 10
	JR	C, TCFG_LEFT_SCALE_DONE
	LD	D, A
	JR	TCFG_LEFT_SCALE_LOOP
TCFG_LEFT_SCALE_DONE:

	LD	B, TCFG_ORG_ROW
	LD	A, (CFG_COLS)
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, 'C'
	CALL	PRTCHR

	LD	A, (CFG_ROWS)
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	C, TCFG_ORG_COL
	CALL	TCFG_ANSI_AT
	LD	A, 'R'
	CALL	PRTCHR

	LD	A, (CFG_ROWS)
	ADD	A, TCFG_ORG_ROW - 1
	LD	B, A
	LD	A, (CFG_COLS)
	ADD	A, TCFG_ORG_COL - 1
	LD	C, A
	CALL	TCFG_ANSI_AT
	LD	A, 'X'
	CALL	PRTCHR

	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_ANSI_AT:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A, 27
	CALL	PRTCHR
	LD	A, '['
	CALL	PRTCHR
	PUSH	BC
	LD	A, B
	CALL	PRTDECB
	LD	A, $3B
	CALL	PRTCHR
	POP	BC
	LD	A, C
	CALL	PRTDECB
	LD	A, 'H'
	CALL	PRTCHR
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

TCFG_GETCH:
	CALL	GETKEY
	OR	A
	JR	Z, TCFG_GETCH
	RET

TCFG_CLRHOME:
	PUSH	AF
	LD	A, (CFG_TERM)
	OR	A
	JR	NZ, TCFG_CLRHOME1
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	JR	Z, TCFG_CLRHOME0
TCFG_CLRHOME1:
	LD	DE, TCFG_SEQ_CLR
	CALL	PRTSTR
TCFG_CLRHOME0:
	POP	AF
	RET

TCFG_EL2:
	PUSH	AF
	LD	A, (CFG_TERM)
	OR	A
	JR	NZ, TCFG_EL21
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	JR	Z, TCFG_EL20
TCFG_EL21:
	LD	DE, TCFG_SEQ_EL2
	CALL	PRTSTR
TCFG_EL20:
	POP	AF
	RET

TCFG_COL_HDR:
	LD	DE, TCFG_SEQ_CYAN
	JP	TCFG_EMIT

TCFG_COL_PRM:
	LD	DE, TCFG_SEQ_YEL
	JP	TCFG_EMIT

TCFG_COL_OK:
	LD	DE, TCFG_SEQ_GRN
	JP	TCFG_EMIT

TCFG_COL_RST:
	LD	DE, TCFG_SEQ_RST
	JP	TCFG_EMIT

TCFG_EMIT:
	PUSH	AF
	LD	A, (CFG_FLAGS)
	AND	CFGF_ANSI
	JR	Z, TCFG_EMIT0
	CALL	PRTSTR
TCFG_EMIT0:
	POP	AF
	RET

;===============================================================================
; Command tail parsing
;===============================================================================

; Parse one token from command tail.
; Supported values (case-insensitive):
;   PLAIN/0, VT100/1, ANSI/2 -> ERR_OK, ARG_TERM set
;   SHOW                     -> ERR_SHOW
;   VERIFY                   -> ERR_VERIFY
;   (no token)               -> ERR_NO_ARG (interactive mode)
PARSE_MODE_ARG:
	LD	HL, $0080
	LD	B, (HL)
	INC	HL

PARSE_SKIP_SPACES:
	LD	A, B
	OR	A
	JP	Z, PARSE_NO_ARG
	LD	A, (HL)
	CP	' '
	JR	NZ, PARSE_COPY_START
	INC	HL
	DEC	B
	JR	PARSE_SKIP_SPACES

PARSE_COPY_START:
	LD	DE, ARG_BUFFER
	LD	C, 0
PARSE_COPY_LOOP:
	LD	A, B
	OR	A
	JR	Z, PARSE_COPY_DONE
	LD	A, (HL)
	CP	' '
	JR	Z, PARSE_COPY_DONE
	LD	A, C
	CP	15
	JP	NC, PARSE_BAD_ARG
	LD	A, (HL)
	LD	(DE), A
	INC	DE
	INC	HL
	DEC	B
	INC	C
	JR	PARSE_COPY_LOOP

PARSE_COPY_DONE:
	XOR	A
	LD	(DE), A

	; Skip trailing spaces.
PARSE_TAIL_SPACES:
	LD	A, B
	OR	A
	JR	Z, PARSE_MAP
	LD	A, (HL)
	CP	' '
	JP	NZ, PARSE_BAD_ARG
	INC	HL
	DEC	B
	JR	PARSE_TAIL_SPACES

PARSE_MAP:
	LD	HL, ARG_BUFFER
	LD	A, (HL)
	OR	A
	JP	Z, PARSE_NO_ARG
	LD	DE, TOK_SHOW
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SHOW
	LD	DE, TOK_VERIFY
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_VERIFY

	LD	DE, TOK_PLAIN
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_PLAIN
	LD	DE, TOK_ZERO
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_PLAIN

	LD	DE, TOK_VT100
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_VT
	LD	DE, TOK_ONE
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_VT

	LD	DE, TOK_ANSI
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_ANSI
	LD	DE, TOK_TWO
	CALL	MATCH_TOKEN
	OR	A
	JP	Z, PARSE_SET_ANSI

PARSE_BAD_ARG:
	LD	A, ERR_BAD_ARG
	RET

PARSE_NO_ARG:
	LD	A, ERR_NO_ARG
	RET

PARSE_SHOW:
	LD	A, ERR_SHOW
	RET

PARSE_SET_PLAIN:
	XOR	A
	LD	(ARG_TERM), A
	XOR	A
	RET

PARSE_SET_VT:
	LD	A, TERM_VT
	LD	(ARG_TERM), A
	XOR	A
	RET

PARSE_SET_ANSI:
	LD	A, TERM_ANSI
	LD	(ARG_TERM), A
	XOR	A
	RET

PARSE_VERIFY:
	LD	A, ERR_VERIFY
	RET

; Compare zero-terminated ARG_BUFFER token (HL) against token at DE.
; Case-insensitive for A-Z.
; Return A=0 match, A=1 no match.
MATCH_TOKEN:
	PUSH	HL
	PUSH	DE
MATCH_LOOP:
	LD	A, (HL)
	CALL	TO_UPPER
	LD	B, A
	LD	A, (DE)
	CALL	TO_UPPER
	CP	B
	JR	NZ, MATCH_NO
	OR	A
	JR	Z, MATCH_YES
	INC	HL
	INC	DE
	JR	MATCH_LOOP

MATCH_NO:
	POP	DE
	POP	HL
	LD	A, 1
	RET

MATCH_YES:
	POP	DE
	POP	HL
	XOR	A
	RET

TO_UPPER:
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	32
	RET

;===============================================================================
; Console I/O helpers
;===============================================================================

; Get a keystroke from CP/M: A=char (NZ) or A=0 (Z) if none pending.
GETKEY:
	LD	C, 6		; BDOS direct console I/O
	LD	E, $FF	; get character if available
	CALL	BDOS
	OR	A
	RET

FLUSHKEYS:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
FLUSHKEYS1:
	CALL	GETKEY
	JR	Z, FLUSHKEYS2
	JR	FLUSHKEYS1
FLUSHKEYS2:
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

; Print the byte in A (0-255) as decimal, suppressing leading zeros.
PRTDECB:
	PUSH	BC
	PUSH	DE
	LD	B, 0		; leading-zero suppression flag
	LD	C, 100
	CALL	PRTDECB_DIG
	LD	C, 10
	CALL	PRTDECB_DIG
	ADD	A, '0'
	CALL	PRTCHR
	POP	DE
	POP	BC
	RET

; Divide A by C; print quotient digit unless leading zero; return remainder in A.
PRTDECB_DIG:
	LD	D, 0
PRTDECB_DIG0:
	CP	C
	JR	C, PTDECB_DIG1
	SUB	C
	INC	D
	JR	PRTDECB_DIG0
PTDECB_DIG1:
	LD	E, A		; remainder
	LD	A, D
	OR	A
	JR	NZ, PTDECB_DIG2
	LD	A, B
	OR	A
	JR	Z, PTDECB_DIG3
PTDECB_DIG2:
	LD	B, $FF
	LD	A, D
	ADD	A, '0'
	CALL	PRTCHR
PTDECB_DIG3:
	LD	A, E
	RET

; Print the zero-terminated string addressed by DE.
PRTSTR:
	PUSH	AF
	PUSH	DE

CFG_PRTSTR_LOOP:
	LD	A, (DE)
	OR	A
	JR	Z, CFG_PRTSTR_DONE
	CALL	PRTCHR
	INC	DE
	JR	CFG_PRTSTR_LOOP

CFG_PRTSTR_DONE:
	POP	DE
	POP	AF
	RET

; Print the character in A via CP/M BDOS function 2.
; Preserves AF: CP/M Plus / ZPM3 BDOS fn 2 returns A=0, which broke
; back-to-back PRTCHR calls (e.g. 3-space ruler erase emitted space+NUL+NUL).
PRTCHR:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E, A
	LD	C, $02
	CALL	BDOS
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

CRLF2:
	CALL	CRLF
CRLF:
	PUSH	AF
	LD	A, 13
	CALL	PRTCHR
	LD	A, 10
	CALL	PRTCHR
	POP	AF
	RET

;===============================================================================
; Messages and data
;===============================================================================

MSG_BANNER:
	.DB	"VibeTune Config Utility v", VT_VERSION, ", ", VT_BUILD_DATE, 0
MSG_USAGE:
	.DB	"Usage: VTUNECFG [plain|vt100|ansi|show|verify]  (no arg = interactive setup)", 0
MSG_ERR_BAD_ARG:
	.DB	"Error: mode must be plain, vt100, ansi, show, or verify.", 0
MSG_ERR_WRITE:
	.DB	"Error: unable to write VTUNE.CFG.", 0
MSG_OK_PREFIX:
	.DB	"Wrote VTUNE.CFG mode: ", 0
MSG_SHOW_MISSING:
	.DB	"VTUNE.CFG not found; using default settings.", 0
MSG_SHOW_INVALID:
	.DB	"VTUNE.CFG invalid; using default settings.", 0
MSG_VERIFY_OK:
	.DB	"VTUNE.CFG verify: PASS", 0
MSG_VERIFY_FAIL:
	.DB	"VTUNE.CFG verify: FAIL", 0

MSG_CFGMODE:
	.DB	"Configuration mode", 0
MSG_CFGFOUND:
	.DB	"Loaded existing VTUNE.CFG:", 0
MSG_CFGDEFAULT:
	.DB	"No VTUNE.CFG found, using built-in defaults:", 0
MSG_CFGINVALID:
	.DB	"VTUNE.CFG invalid, using built-in defaults:", 0
MSG_CFGSAVED:
	.DB	"Saved VTUNE.CFG", 0
MSG_CFGTERM:
	.DB	"  Term type: ", 0
MSG_CFGANSI:
	.DB	"  ANSI colour: ", 0
MSG_CFGSIZE:
	.DB	"  Size: ", 0
MSG_CFGCARD1:
	.DB	"  Primary AY: ", 0
MSG_CFGCARD2:
	.DB	"  Second AY:  ", 0
MSG_CFGTS:
	.DB	"  TurboSound: ", 0
MSG_CARD1MENU:
	.DB	"Primary sound card? A=auto-detect, M=MSX ($A0/$A1), R=RC2014 ($D8/$D0), E=EB ($68/$60), C=Coleco ($50/$51)", 0
MSG_CARD2MENU:
	.DB	"Second sound card (dual)? M=MSX, R=RC2014, E=EB, C=Coleco (must differ from primary)", 0
MSG_CARDPROMPT:
	.DB	"Choice [Enter keeps ", 0
MSG_CARD_AUTO:
	.DB	"auto-detect", 0
MSG_CARD_NONE:
	.DB	"(not set)", 0
MSG_CARD_MSX:
	.DB	"MSX ($A0H/$A1H)", 0
MSG_CARD_RC:
	.DB	"RC2014 ($D8H/$D0H)", 0
MSG_CARD_EB:
	.DB	"EB ($68H/$60H)", 0
MSG_CARD_COLECO:
	.DB	"Coleco ($50H/$51H)", 0
MSG_CARD_SAME:
	.DB	"Second card must differ from primary.", 0
MSG_TSMENU:
	.DB	"TurboSound mode? A=auto (Hi-Z=>AVR module), D=dual card (needs second AY in CFG), M=AVR module FF/FE", 0
MSG_TSPROMPT:
	.DB	"Choice [Enter keeps ", 0
MSG_TS_AUTO:
	.DB	"auto-detect", 0
MSG_TS_DUAL:
	.DB	"dual card", 0
MSG_TS_MOD:
	.DB	"AVR module", 0
MSG_TERMMENU:
	.DB	"Term type? P=plain, V=VTxxx, A=ANSI", 0
MSG_TERMPROMPT:
	.DB	"Choice [Enter keeps ", 0
MSG_ANSIPROMPT:
	.DB	"ANSI colour? Y/N [Enter keeps ", 0
MSG_PROMPTEND:
	.DB	"]: ", 0
MSG_TERM_PLAIN:
	.DB	"plain", 0
MSG_TERM_VT:
	.DB	"VTxxx", 0
MSG_TERM_ANSI:
	.DB	"ANSI", 0
MSG_YES:
	.DB	"yes", 0
MSG_NO:
	.DB	"no", 0
MSG_TUNETITLE:
	.DB	"Adjust visible limits until C, R, and X are just visible.", 0
MSG_TUNEKEYS:
	.DB	"Adjustment Keys: a/d for columns and w/s for rows, or arrow keys, Esc save+quit", 0
MSG_TUNECURR:
	.DB	"Current size: ", 0
MSG_TUNEMAX:
	.DB	" (max: 150 x 50)   ", 0

TCFG_SEQ_CLR:
	.DB	27, '[', '2', 'J', 27, '[', 'H', 0
TCFG_SEQ_EL2:
	.DB	27, '[', '2', 'K', 0
TCFG_SEQ_CYAN:
	.DB	27, '[', '3', '6', 'm', 0
TCFG_SEQ_YEL:
	.DB	27, '[', '3', '3', 'm', 0
TCFG_SEQ_GRN:
	.DB	27, '[', '3', '2', 'm', 0
TCFG_SEQ_RST:
	.DB	27, '[', '0', 'm', 0

TOK_PLAIN:
	.DB	"PLAIN", 0
TOK_VT100:
	.DB	"VT100", 0
TOK_ANSI:
	.DB	"ANSI", 0
TOK_ZERO:
	.DB	"0", 0
TOK_ONE:
	.DB	"1", 0
TOK_TWO:
	.DB	"2", 0
TOK_SHOW:
	.DB	"SHOW", 0
TOK_VERIFY:
	.DB	"VERIFY", 0

CFG_NAME:
	.DB	"VTUNE   CFG"

; Config record (contiguous for verify compare)
CFG_TERM:
	.DB	TERM_PLAIN
CFG_FLAGS:
	.DB	0
CFG_ROWS:
	.DB	CFG_DFL_ROWS
CFG_COLS:
	.DB	CFG_DFL_COLS
CFG_TSTOPO:
	.DB	TS_TOPO_AUTO
CFG_CARD1:
	.DB	AY_CARD_AUTO
CFG_CARD2:
	.DB	AY_CARD_AUTO
BEFORE_TERM:
	.DB	0, 0, 0, 0, 0, 0, 0
ARG_TERM:
	.DB	TERM_PLAIN
CFG_LOAD_STAT:
	.DB	0
TCFG_PREV_COLS:
	.DB	0
TCFG_PREV_ROWS:
	.DB	0
ARG_BUFFER:
	.DS	16
CFG_FCB:
	.DS	36
DMA_BUFFER:
	.DS	128

	.END	START
